
# Site settings

# NB! Set your site's url, otherwise stuff will break :)
url: "https://axiezai.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: "/personal"
baseurl: ""

# Google tracking id
google-tracking-id: "UA-125027007-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it
force-https: True

#############
# HTML Head #
#############
lang: "en"
author: "Xi He Xie"
title: "{ ludus }"
description: "The Latin word Ludus (plural ludi) means school in latin but it could also mean sport or game."
keywords: "blog, personal, jekyll, theme"
favicon: "/img/favicon.ico"

################
# Header layout #
################
black-favicon: "/img/black-brain.ico"
# logo: "/img/author.png" # leave blank if you don't want a logo

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 4500
lines: # You can add HTML Tags in the Text
  - text: "<q>PhD stands for permanent head damage</q> - one of my teachers."
  - text: "<q>You're such a nerd.</q> - A non-academic."

me-img: "/img/author.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################
web-app-mode: True

# Icons for Web App mode
icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########
enable-gesture-navigation: True

post-preview-words: 96

paginate: 10 

email-share: True
fb-share: False 
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False 
tumblr-share: False 
pinterest-share: True
pocket-share: False 
vkontakte-share: False 

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############
events:
  - image: "img/timeline/ttd-logo.png"
    date: "October 2022"
    description: "Became a data scientist!"
  - image: "/img/timeline/spidertocat.png"
    date: "December 2021"
    description: "Finished the Ph.D!"
  - image: "/img/timeline/neuromatch-icon.png"
    date: "August 2021"
    description: "Attended Neuromatch Deep Learning!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "June 2020"
    description: "Organized Brainhack NY!"
  - image: "/img/timeline/nyc-icon.png"
    date: "February 2021"
    description: "Settled back home in NYC!"
  - image: "/img/timeline/repronim-icon.png"
    date: "March 2020 - Today"
    description: "Became a ReproNim/INCF Fellow!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "August 2018"
    description: "Attended Neurohackademy in Seattle!"
  - image: "/img/timeline/sf-icon.png"
    date: "April 2018"
    description: "Moved to San Francisco!"

# First image of the Timeline
timeline-img: "/img/author.png"

###########
# Contact #
###########
email: "xihe.init@gmail.com"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################
# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Often compelled, sometimes high on coffee, very random attempts to <a href='https://tom.preston-werner.com/2008/11/17/blogging-like-a-hacker.html'>blog like a hacker</a>."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################
social:
  - title: "twitter"
    url: "https://twitter.com/axiezai"
  - title: "github"
    url: "https://github.com/axiezai"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/jxxie/"
  - title: "instagram"
    url: "https://www.instagram.com/axiezai"

############
# 404 page #
############
err-404-img: "/img/labtocat.png"

# ##################
# # GPG on Keybase #
# ##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site
exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path
paginate_path: "blog/page:num/"

# Enable minification SASS
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
  - webrick